version: '3'

services:
  minerva-demo:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    links:
      - db
  db:
    image: postgres:10-alpine
    env_file:
      - '.env'
    expose:
      - 5432
